-- Migration: Enable pgvector extension and create RAG tables
-- Purpose: Setup semantic search infrastructure for TaxShield RAG
-- Date: 2026-04-06

-- ============================================================
-- Step 1: Enable pgvector extension
-- ============================================================
CREATE EXTENSION IF NOT EXISTS vector;

-- ============================================================
-- Step 2: Create documents table (if not exists)
-- ============================================================
CREATE TABLE IF NOT EXISTS documents (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    doc_id TEXT UNIQUE NOT NULL,
    title TEXT NOT NULL,
    content_text TEXT,
    source_url TEXT,
    metadata JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_documents_doc_id ON documents(doc_id);
CREATE INDEX IF NOT EXISTS idx_documents_created_at ON documents(created_at);

-- ============================================================
-- Step 3: Create document_chunks table with pgvector embeddings
-- ============================================================
CREATE TABLE IF NOT EXISTS document_chunks (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    document_id BIGINT NOT NULL REFERENCES documents(id) ON DELETE CASCADE,
    chunk_index INTEGER NOT NULL,
    chunk_text TEXT NOT NULL,
    embedding vector(1536),  -- OpenAI text-embedding-3-small dimension
    embedding_model TEXT DEFAULT 'text-embedding-3-small',
    bm25_metadata JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_chunks_document_id ON document_chunks(document_id);
CREATE INDEX IF NOT EXISTS idx_chunks_embedding ON document_chunks USING ivfflat (embedding vector_cosine_ops) WITH (lists = 100);
CREATE INDEX IF NOT EXISTS idx_chunks_created_at ON document_chunks(created_at);

-- ============================================================
-- Step 4: Create search performance index (HNSW alternative)
-- ============================================================
-- HNSW is better for high-dimensional searches but requires pg_partman
-- For now, use IVFFLAT which is stable and performant
-- To enable HNSW when available:
-- CREATE INDEX idx_chunks_embedding_hnsw ON document_chunks 
--   USING hnsw (embedding vector_cosine_ops) WITH (m = 16, ef_construction = 64);

-- ============================================================
-- Step 5: Create RAG audit trail table
-- ============================================================
CREATE TABLE IF NOT EXISTS rag_queries (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    query_text TEXT NOT NULL,
    query_embedding vector(1536),
    results_count INTEGER,
    top_chunks_used JSONB,
    llm_response_id TEXT,
    response_confidence FLOAT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_rag_queries_created_at ON rag_queries(created_at);

-- ============================================================
-- Step 6: Helper function for semantic search
-- ============================================================
CREATE OR REPLACE FUNCTION search_chunks_by_embedding(
    query_embedding vector,
    match_count INT DEFAULT 5,
    similarity_threshold FLOAT DEFAULT 0.3
)
RETURNS TABLE (
    chunk_id BIGINT,
    document_id BIGINT,
    chunk_index INTEGER,
    chunk_text TEXT,
    similarity FLOAT
) AS $$
BEGIN
    RETURN QUERY
    SELECT 
        dc.id,
        dc.document_id,
        dc.chunk_index,
        dc.chunk_text,
        (1 - (dc.embedding <=> query_embedding))::FLOAT AS similarity
    FROM document_chunks dc
    WHERE dc.embedding IS NOT NULL
        AND (1 - (dc.embedding <=> query_embedding)) >= similarity_threshold
    ORDER BY dc.embedding <=> query_embedding
    LIMIT match_count;
END;
$$ LANGUAGE plpgsql;

-- ============================================================
-- Step 7: Cleanup function (mark chunks as deleted)
-- ============================================================
CREATE OR REPLACE FUNCTION delete_document_chunks(doc_id TEXT)
RETURNS INT AS $$
DECLARE
    deleted_count INT;
BEGIN
    DELETE FROM document_chunks
    WHERE document_id = (SELECT id FROM documents WHERE doc_id = doc_id);
    GET DIAGNOSTICS deleted_count = ROW_COUNT;
    RETURN deleted_count;
END;
$$ LANGUAGE plpgsql;

-- ============================================================
-- Step 8: Grant permissions (if needed for RLS)
-- ============================================================
-- Uncomment for production RLS setup
-- ALTER TABLE documents ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE document_chunks ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE rag_queries ENABLE ROW LEVEL SECURITY;

COMMIT;
