-- Migration: Setup Row-Level Security (RLS) for TaxShield RAG
-- Purpose: Implement security policies for multi-tenant data isolation
-- Date: 2026-04-06

-- ============================================================
-- NOTE: This requires authentication configuration in Supabase
-- Set these policies AFTER user authentication is setup
-- ============================================================

-- ============================================================
-- Step 1: Enable RLS on RAG tables
-- ============================================================
ALTER TABLE documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE document_chunks ENABLE ROW LEVEL SECURITY;
ALTER TABLE rag_queries ENABLE ROW LEVEL SECURITY;

-- ============================================================
-- Step 2: Create RLS policies for documents table
-- ============================================================
-- Allow authenticated users to read all documents (public knowledge base)
CREATE POLICY "documents_select_authenticated" ON documents
    FOR SELECT
    USING (auth.role() = 'authenticated');

-- Allow service role to insert documents
CREATE POLICY "documents_insert_service_role" ON documents
    FOR INSERT
    WITH CHECK (auth.role() = 'service_role');

-- Allow service role to update documents
CREATE POLICY "documents_update_service_role" ON documents
    FOR UPDATE
    USING (auth.role() = 'service_role')
    WITH CHECK (auth.role() = 'service_role');

-- Allow service role to delete documents
CREATE POLICY "documents_delete_service_role" ON documents
    FOR DELETE
    USING (auth.role() = 'service_role');

-- ============================================================
-- Step 3: Create RLS policies for document_chunks table
-- ============================================================
-- Allow authenticated users to read all chunks (semantic search)
CREATE POLICY "chunks_select_authenticated" ON document_chunks
    FOR SELECT
    USING (auth.role() = 'authenticated');

-- Allow service role to insert chunks
CREATE POLICY "chunks_insert_service_role" ON document_chunks
    FOR INSERT
    WITH CHECK (auth.role() = 'service_role');

-- Allow service role to update chunks
CREATE POLICY "chunks_update_service_role" ON document_chunks
    FOR UPDATE
    USING (auth.role() = 'service_role')
    WITH CHECK (auth.role() = 'service_role');

-- Allow service role to delete chunks
CREATE POLICY "chunks_delete_service_role" ON document_chunks
    FOR DELETE
    USING (auth.role() = 'service_role');

-- ============================================================
-- Step 4: Create RLS policies for rag_queries table
-- ============================================================
-- Allow users to read only their own queries
CREATE POLICY "queries_select_own" ON rag_queries
    FOR SELECT
    USING (auth.uid()::text = (auth.jwt() ->> 'sub') OR auth.role() = 'service_role');

-- Allow authenticated users to insert queries
CREATE POLICY "queries_insert_authenticated" ON rag_queries
    FOR INSERT
    WITH CHECK (auth.role() = 'authenticated' OR auth.role() = 'service_role');

-- Allow users to update their own queries
CREATE POLICY "queries_update_own" ON rag_queries
    FOR UPDATE
    USING (auth.uid()::text = (auth.jwt() ->> 'sub') OR auth.role() = 'service_role')
    WITH CHECK (auth.uid()::text = (auth.jwt() ->> 'sub') OR auth.role() = 'service_role');

-- ============================================================
-- Step 5: Grant permissions to anon and authenticated roles
-- ============================================================
-- Anon role (unauthenticated) - no access
-- Authenticated role - select only (limited)
-- Service role - full access (backend operations)

GRANT USAGE ON SCHEMA public TO authenticated, anon;
GRANT SELECT ON documents TO authenticated, anon;
GRANT SELECT ON document_chunks TO authenticated, anon;
GRANT SELECT ON rag_queries TO authenticated;

-- Service role gets full access
GRANT ALL ON documents TO service_role;
GRANT ALL ON document_chunks TO service_role;
GRANT ALL ON rag_queries TO service_role;

-- ============================================================
-- Step 6: Add security table for audit logging (optional)
-- ============================================================
CREATE TABLE IF NOT EXISTS security_audit (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    table_name TEXT NOT NULL,
    operation TEXT NOT NULL,
    user_id UUID,
    record_id BIGINT,
    old_data JSONB,
    new_data JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX idx_security_audit_created_at ON security_audit(created_at);
CREATE INDEX idx_security_audit_user_id ON security_audit(user_id);

-- ============================================================
-- Step 7: Create function for audit trailing
-- ============================================================
CREATE OR REPLACE FUNCTION audit_log()
RETURNS TRIGGER AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        INSERT INTO security_audit (table_name, operation, user_id, new_data)
        VALUES (TG_TABLE_NAME, TG_OP, auth.uid(), row_to_json(NEW));
    ELSIF TG_OP = 'UPDATE' THEN
        INSERT INTO security_audit (table_name, operation, user_id, old_data, new_data)
        VALUES (TG_TABLE_NAME, TG_OP, auth.uid(), row_to_json(OLD), row_to_json(NEW));
    ELSIF TG_OP = 'DELETE' THEN
        INSERT INTO security_audit (table_name, operation, user_id, old_data)
        VALUES (TG_TABLE_NAME, TG_OP, auth.uid(), row_to_json(OLD));
    END IF;
    RETURN NULL;
END
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Optional: Enable audit logging on sensitive tables
-- CREATE TRIGGER documents_audit_trigger AFTER INSERT OR UPDATE OR DELETE ON documents
--     FOR EACH ROW EXECUTE FUNCTION audit_log();
-- CREATE TRIGGER chunks_audit_trigger AFTER INSERT OR UPDATE OR DELETE ON document_chunks
--     FOR EACH ROW EXECUTE FUNCTION audit_log();

COMMIT;
