-- REPAIR MIGRATION: Add missing columns to documents table
-- This fixes the missing doc_id column issue

-- ============================================================
-- DROP and RECREATE documents table with correct schema
-- ============================================================

-- First, backup existing data if any
CREATE TABLE IF NOT EXISTS documents_backup AS SELECT * FROM documents;

-- Drop the old table and dependencies
DROP TABLE IF EXISTS document_chunks CASCADE;
DROP TABLE IF EXISTS documents CASCADE;

-- Recreate documents table with ALL required columns
CREATE TABLE documents (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    doc_id TEXT UNIQUE NOT NULL,
    title TEXT NOT NULL,
    content_text TEXT,
    source_url TEXT,
    metadata JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create indices
CREATE INDEX idx_documents_doc_id ON documents(doc_id);
CREATE INDEX idx_documents_created_at ON documents(created_at);

-- ============================================================
-- Recreate document_chunks table with pgvector embeddings
-- ============================================================
CREATE TABLE document_chunks (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    document_id BIGINT NOT NULL REFERENCES documents(id) ON DELETE CASCADE,
    chunk_index INTEGER NOT NULL,
    chunk_text TEXT NOT NULL,
    embedding vector(1536),
    embedding_model TEXT DEFAULT 'text-embedding-3-small',
    bm25_metadata JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create indices
CREATE INDEX idx_chunks_document_id ON document_chunks(document_id);
CREATE INDEX idx_chunks_embedding ON document_chunks USING ivfflat (embedding vector_cosine_ops) WITH (lists = 100);
CREATE INDEX idx_chunks_created_at ON document_chunks(created_at);

-- ============================================================
-- Recreate pgvector search function
-- ============================================================
CREATE OR REPLACE FUNCTION search_chunks_by_embedding(
    query_embedding vector,
    match_count INT DEFAULT 5,
    similarity_threshold FLOAT DEFAULT 0.3
)
RETURNS TABLE (
    chunk_id BIGINT,
    document_id BIGINT,
    chunk_index INTEGER,
    chunk_text TEXT,
    similarity FLOAT
) AS $$
BEGIN
    RETURN QUERY
    SELECT 
        dc.id,
        dc.document_id,
        dc.chunk_index,
        dc.chunk_text,
        (1 - (dc.embedding <=> query_embedding))::FLOAT AS similarity
    FROM document_chunks dc
    WHERE dc.embedding IS NOT NULL
        AND (1 - (dc.embedding <=> query_embedding)) >= similarity_threshold
    ORDER BY dc.embedding <=> query_embedding
    LIMIT match_count;
END;
$$ LANGUAGE plpgsql;

-- ============================================================
-- Recreate delete function
-- ============================================================
CREATE OR REPLACE FUNCTION delete_document_chunks(doc_id TEXT)
RETURNS INT AS $$
DECLARE
    deleted_count INT;
BEGIN
    DELETE FROM document_chunks
    WHERE document_id = (SELECT id FROM documents WHERE doc_id = doc_id);
    GET DIAGNOSTICS deleted_count = ROW_COUNT;
    RETURN deleted_count;
END;
$$ LANGUAGE plpgsql;

-- ============================================================
-- Enable RLS
-- ============================================================
ALTER TABLE documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE document_chunks ENABLE ROW LEVEL SECURITY;

-- ============================================================
-- Create RLS policies for documents
-- ============================================================
DROP POLICY IF EXISTS documents_select_authenticated ON documents;
DROP POLICY IF EXISTS documents_insert_service_role ON documents;
DROP POLICY IF EXISTS documents_update_service_role ON documents;
DROP POLICY IF EXISTS documents_delete_service_role ON documents;

CREATE POLICY documents_select_authenticated ON documents
    FOR SELECT
    USING (auth.role() = 'authenticated');

CREATE POLICY documents_insert_service_role ON documents
    FOR INSERT
    WITH CHECK (auth.role() = 'service_role');

CREATE POLICY documents_update_service_role ON documents
    FOR UPDATE
    USING (auth.role() = 'service_role')
    WITH CHECK (auth.role() = 'service_role');

CREATE POLICY documents_delete_service_role ON documents
    FOR DELETE
    USING (auth.role() = 'service_role');

-- ============================================================
-- Create RLS policies for chunks
-- ============================================================
DROP POLICY IF EXISTS chunks_select_authenticated ON document_chunks;
DROP POLICY IF EXISTS chunks_insert_service_role ON document_chunks;
DROP POLICY IF EXISTS chunks_update_service_role ON document_chunks;
DROP POLICY IF EXISTS chunks_delete_service_role ON document_chunks;

CREATE POLICY chunks_select_authenticated ON document_chunks
    FOR SELECT
    USING (auth.role() = 'authenticated');

CREATE POLICY chunks_insert_service_role ON document_chunks
    FOR INSERT
    WITH CHECK (auth.role() = 'service_role');

CREATE POLICY chunks_update_service_role ON document_chunks
    FOR UPDATE
    USING (auth.role() = 'service_role')
    WITH CHECK (auth.role() = 'service_role');

CREATE POLICY chunks_delete_service_role ON document_chunks
    FOR DELETE
    USING (auth.role() = 'service_role');

-- ============================================================
-- Grant permissions
-- ============================================================
GRANT USAGE ON SCHEMA public TO authenticated, anon;
GRANT SELECT ON documents TO authenticated, anon;
GRANT SELECT ON document_chunks TO authenticated, anon;
GRANT ALL ON documents TO service_role;
GRANT ALL ON document_chunks TO service_role;

COMMIT;
