"""fix_response_deadline_type

Revision ID: 265444b8b666
Revises: 0af1eda54e25
Create Date: 2026-04-04 11:49:26.553258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '265444b8b666'
down_revision: Union[str, Sequence[str], None] = '0af1eda54e25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('user_email', sa.String(), nullable=True),
    sa.Column('user_role', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('resource_type', sa.String(), nullable=False),
    sa.Column('resource_id', sa.String(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_action', 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index('ix_audit_logs_resource', 'audit_logs', ['resource_type', 'resource_id'], unique=False)
    op.create_table('cases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('client_name', sa.String(), nullable=True),
    sa.Column('client_interview', sa.JSON(), nullable=True),
    sa.Column('legal_analysis', sa.Text(), nullable=True),
    sa.Column('relevant_circulars', sa.JSON(), nullable=True),
    sa.Column('relevant_case_laws', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id')
    )
    op.create_table('drafts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('notice_id', sa.String(length=36), nullable=False),
    sa.Column('draft_content', sa.Text(), nullable=False),
    sa.Column('defense_strategy', sa.Text(), nullable=True),
    sa.Column('supporting_documents', sa.JSON(), nullable=True),
    sa.Column('procedural_compliance', sa.Boolean(), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notices',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('notice_text', sa.Text(), nullable=True),
    sa.Column('entities', sa.JSON(), nullable=True),
    sa.Column('notice_annotations', sa.JSON(), nullable=True),
    sa.Column('processing_status', sa.String(), nullable=True),
    sa.Column('risk_level', sa.String(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('risk_reasoning', sa.Text(), nullable=True),
    sa.Column('is_time_barred', sa.Boolean(), nullable=True),
    sa.Column('time_bar_detail', sa.JSON(), nullable=True),
    sa.Column('fy', sa.String(), nullable=True),
    sa.Column('section', sa.String(), nullable=True),
    sa.Column('notice_type', sa.String(), nullable=True),
    sa.Column('demand_amount', sa.Float(), nullable=True),
    sa.Column('response_deadline', sa.Date(), nullable=True),
    sa.Column('draft_reply', sa.Text(), nullable=True),
    sa.Column('draft_status', sa.String(), nullable=True),
    sa.Column('verification_status', sa.String(), nullable=True),
    sa.Column('verification_score', sa.Float(), nullable=True),
    sa.Column('verification_issues', sa.JSON(), nullable=True),
    sa.Column('accuracy_report', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id')
    )
    op.create_index(op.f('ix_notices_created_at'), 'notices', ['created_at'], unique=False)
    op.create_index('ix_notices_draft_status', 'notices', ['draft_status'], unique=False)
    op.create_index('ix_notices_risk_level', 'notices', ['risk_level'], unique=False)
    op.create_index('ix_notices_status', 'notices', ['status'], unique=False)
    op.create_index(op.f('ix_notices_user_id'), 'notices', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=True),
    sa.Column('email_verification_token', sa.String(), nullable=True),
    sa.Column('email_token_expires', sa.DateTime(), nullable=True),
    sa.Column('totp_secret', sa.String(), nullable=True),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_notices_user_id'), table_name='notices')
    op.drop_index('ix_notices_status', table_name='notices')
    op.drop_index('ix_notices_risk_level', table_name='notices')
    op.drop_index('ix_notices_draft_status', table_name='notices')
    op.drop_index(op.f('ix_notices_created_at'), table_name='notices')
    op.drop_table('notices')
    op.drop_table('drafts')
    op.drop_table('cases')
    op.drop_index('ix_audit_logs_resource', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_action', table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
